export const stationList = [
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SWA',
		Station_Contacts: '044 - 2379 2047',
		Station_Id: '101',
		Station_Latitude: 13.107064,
		Station_LineColour: 'Blue',
		Station_LongName: 'Washermenpet',
		Station_Longitude: 80.280528,
		Station_Priority: 27,
		Station_ShortName: 'Washermenpet',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SMA',
		Station_Contacts: '044 - 23792046',
		Station_Id: '102',
		Station_Latitude: 13.09542,
		Station_LineColour: 'Blue',
		Station_LongName: 'Mannadi',
		Station_Longitude: 80.286164,
		Station_Priority: 28,
		Station_ShortName: 'Mannadi',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SHC',
		Station_Contacts: '044 - 23792045',
		Station_Id: '103',
		Station_Latitude: 13.087068,
		Station_LineColour: 'Blue',
		Station_LongName: 'High Court',
		Station_Longitude: 80.285021,
		Station_Priority: 29,
		Station_ShortName: 'High Court',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SCC',
		Station_Contacts: '044-23792044',
		Station_Id: '104',
		Station_Latitude: 13.081426,
		Station_LineColour: 'i1',
		Station_LongName: 'Puratchi Thalaivar Dr.M.G.Ramachandran Central Metro',
		Station_Longitude: 80.272887,
		Station_Priority: 22,
		Station_ShortName: 'Puratchi Thalaivar Dr.M.G.Ramachandran Central Metro',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SGE',
		Station_Contacts: '044 - 2379 2043',
		Station_Id: '105',
		Station_Latitude: 13.069557,
		Station_LineColour: 'Blue',
		Station_LongName: 'Government Estate',
		Station_Longitude: 80.272842,
		Station_Priority: 30,
		Station_ShortName: 'Government Estate',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SLI',
		Station_Contacts: '044 - 2379 2042',
		Station_Id: '106',
		Station_Latitude: 13.064511,
		Station_LineColour: 'Blue',
		Station_LongName: 'LIC',
		Station_Longitude: 80.266065,
		Station_Priority: 31,
		Station_ShortName: 'LIC',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STL',
		Station_Contacts: '044 - 23792041',
		Station_Id: '107',
		Station_Latitude: 13.058198,
		Station_LineColour: 'Blue',
		Station_LongName: 'Thousand Lights',
		Station_Longitude: 80.258056,
		Station_Priority: 32,
		Station_ShortName: 'Thousand Lights',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SGM',
		Station_Contacts: '044 - 23792040',
		Station_Id: '108',
		Station_Latitude: 13.044682,
		Station_LineColour: 'Blue',
		Station_LongName: 'AG - DMS',
		Station_Longitude: 80.248052,
		Station_Priority: 23,
		Station_ShortName: 'AG - DMS',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STE',
		Station_Contacts: '044 - 23792039',
		Station_Id: '109',
		Station_Latitude: 13.037904,
		Station_LineColour: 'Blue',
		Station_LongName: 'Teynampet',
		Station_Longitude: 80.247029,
		Station_Priority: 24,
		Station_ShortName: 'Teynampet',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SCR',
		Station_Contacts: '044 - 23792038',
		Station_Id: '110',
		Station_Latitude: 13.03139,
		Station_LineColour: 'Blue',
		Station_LongName: 'Nandanam',
		Station_Longitude: 80.239969,
		Station_Priority: 25,
		Station_ShortName: 'Nandanam',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SSA',
		Station_Contacts: '044 - 23792137',
		Station_Id: '111',
		Station_Latitude: 13.023717,
		Station_LineColour: 'Blue',
		Station_LongName: 'Saidapet Metro',
		Station_Longitude: 80.228208,
		Station_Priority: 26,
		Station_ShortName: 'Saidapet Metro',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Saidapet, Anna University"\n        }\n]\n',
		Platform_Info:
			'[\n        {\n            "level": "Level 1",\n            "towards": "-"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Airport metro"\n        }\n       \n]',
		Station_Code: 'SLM',
		Station_Contacts: '044 - 2379 2036',
		Station_Id: '112',
		Station_Latitude: 13.014712,
		Station_LineColour: 'Blue',
		Station_LongName: 'Little Mount',
		Station_Longitude: 80.223993,
		Station_Priority: 12,
		Station_ShortName: 'Little Mount',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Suburban Railway Station, Airport"\n        }\n]\n',
		Platform_Info:
			'[\n        {\n            "level": "Level 1",\n            "towards": "Airport"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Little Mount"\n        }\n       \n]\n',
		Station_Code: 'SGU',
		Station_Contacts: '044 - 2379 2035',
		Station_Id: '113',
		Station_Latitude: 13.00924,
		Station_LineColour: 'Blue',
		Station_LongName: 'Guindy',
		Station_Longitude: 80.213199,
		Station_Priority: 11,
		Station_ShortName: 'Guindy',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Airport, Thambaram"\n        },\n{\n            "gate": "GATE B",\n            "towards": "Towards adambakkam, Velacherry"\n        } ,\n{\n            "gate": "GATE C",\n            "towards": "Towards Guindy, Le Merdian"\n        }     \n]\n',
		Platform_Info:
			'[\n        {\n            "level": "Level 1",\n            "towards": "Airport"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Little Mount"\n        },\n {\n            "level": "Level 2",\n            "towards": "St.Thomas Mount"\n        },\n {\n            "level": "Level 2",\n            "towards": "Koyambedu"\n        }\n\n       \n]',
		Station_Code: 'SAL',
		Station_Contacts: '044 - 23792220',
		Station_Id: '114',
		Station_Latitude: 13.004713,
		Station_LineColour: 'i1',
		Station_LongName: 'Arignar Anna Alandur Metro',
		Station_Longitude: 80.20145,
		Station_Priority: 7,
		Station_ShortName: 'Arignar Anna Alandur Metro',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards GST Road"\n        }\n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "Airport"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Little Mount"\n        }   \n]\n',
		Station_Code: 'SOT',
		Station_Contacts: '044 - 2379 2030',
		Station_Id: '115',
		Station_Latitude: 12.999933,
		Station_LineColour: 'Blue',
		Station_LongName: 'Nanganallur Road\t',
		Station_Longitude: 80.193985,
		Station_Priority: 10,
		Station_ShortName: 'Nanganallur Road\t',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [\n     \n    {\n            "gate": "GATE B",\n            "towards": "Towards Airport Cargo Side"\n        }  \n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "Airport"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Little Mount"\n        }   \n]\n',
		Station_Code: 'SME',
		Station_Contacts: '044 - 23792032',
		Station_Id: '116',
		Station_Latitude: 12.987656,
		Station_LineColour: 'Blue',
		Station_LongName: 'Meenambakkam',
		Station_Longitude: 80.176505,
		Station_Priority: 9,
		Station_ShortName: 'Meenambakkam',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards International, Domestic Airport side"\n        },\n{\n            "gate": "GATE B",\n            "towards": "Towards GST Road"\n        }\n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "-"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Little Mount"\n        }   \n]\n',
		Station_Code: 'SAP',
		Station_Contacts: '044 - 23792031',
		Station_Id: '117',
		Station_Latitude: 12.980827,
		Station_LineColour: 'Blue',
		Station_LongName: 'Chennai International Airport',
		Station_Longitude: 80.1642,
		Station_Priority: 8,
		Station_ShortName: 'Chennai International Airport',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SEG',
		Station_Contacts: '044 - 23792266',
		Station_Id: '202',
		Station_Latitude: 13.079059,
		Station_LineColour: 'Green',
		Station_LongName: 'Egmore Metro',
		Station_Longitude: 80.261098,
		Station_Priority: 21,
		Station_ShortName: 'Egmore Metro',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SNP',
		Station_Contacts: '044 - 23792265',
		Station_Id: '203',
		Station_Latitude: 13.078625,
		Station_LineColour: 'Green',
		Station_LongName: 'Nehru Park',
		Station_Longitude: 80.250855,
		Station_Priority: 14,
		Station_ShortName: 'Nehru Park',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SKM',
		Station_Contacts: '044 - 23792264',
		Station_Id: '204',
		Station_Latitude: 13.077508,
		Station_LineColour: 'Green',
		Station_LongName: 'Kilpauk',
		Station_Longitude: 80.242867,
		Station_Priority: 15,
		Station_ShortName: 'Kilpauk',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SPC',
		Station_Contacts: '044 - 23792263',
		Station_Id: '205',
		Station_Latitude: 13.07557,
		Station_LineColour: 'Green',
		Station_LongName: "Pachaiyappa's College",
		Station_Longitude: 80.232347,
		Station_Priority: 16,
		Station_ShortName: "Pachaiyappa's College",
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SSN',
		Station_Contacts: '044 - 23792262',
		Station_Id: '206',
		Station_Latitude: 13.078697,
		Station_LineColour: 'Green',
		Station_LongName: 'Shenoy Nagar',
		Station_Longitude: 80.225133,
		Station_Priority: 17,
		Station_ShortName: 'Shenoy Nagar',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SAE',
		Station_Contacts: '044 - 23762261',
		Station_Id: '207',
		Station_Latitude: 13.084794,
		Station_LineColour: 'Green',
		Station_LongName: 'Anna Nagar East',
		Station_Longitude: 80.21866,
		Station_Priority: 18,
		Station_ShortName: 'Anna Nagar East',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SAT',
		Station_Contacts: '044 - 23792160',
		Station_Id: '208',
		Station_Latitude: 13.084975,
		Station_LineColour: 'Green',
		Station_LongName: 'Anna Nagar Tower',
		Station_Longitude: 80.208727,
		Station_Priority: 19,
		Station_ShortName: 'Anna Nagar Tower',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STI',
		Station_Contacts: '044 - 23792159',
		Station_Id: '209',
		Station_Latitude: 13.085259,
		Station_LineColour: 'Green',
		Station_LongName: 'Thirumangalam',
		Station_Longitude: 80.201575,
		Station_Priority: 20,
		Station_ShortName: 'Thirumangalam',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Poonamallee high road"\n        },\n{\n            "gate": "GATE B",\n            "towards": "Towards Koambedu Market, Omni Bus Stand"\n        }\n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "-"\n        },\n    {\n            "level": "Level 1",\n            "towards": "St.Thomas Mount"\n        },\n{\n            "level": "Level 2",\n            "towards": "-"\n        }   \n]\n',
		Station_Code: 'SKO',
		Station_Contacts: '044 - 23792280',
		Station_Id: '210',
		Station_Latitude: 13.07333,
		Station_LineColour: 'Green',
		Station_LongName: 'Koyambedu',
		Station_Longitude: 80.194869,
		Station_Priority: 1,
		Station_ShortName: 'Koyambedu',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			'[ \n    {\n            "gate": "GATE A",\n            "towards": "Towards C.M.B.T.Local bus stand, Mofussal Bus stand"\n        },\n{\n            "gate": "GATE B",\n            "towards": "Towards Koambedu Market ,Omni Bus Stand"\n        } \n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "St.Thomas Mount"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Koyambedu"\n        }  \n]\n',
		Station_Code: 'SCM',
		Station_Contacts: '044 - 23792270',
		Station_Id: '211',
		Station_Latitude: 13.068575,
		Station_LineColour: 'Green',
		Station_LongName: 'Puratchi Thalaivi Dr.J.Jayalalithaa CMBT Metro',
		Station_Longitude: 80.203882,
		Station_Priority: 2,
		Station_ShortName: 'Puratchi Thalaivi Dr.J.Jayalalithaa CMBT Metro',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Iswarya Mahal Side"\n        },\n{\n            "gate": "GATE B",\n            "towards": "Towards MMDA Colony,Periyar Pathai"\n        }\n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "St.Thomas Mount"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Koyambedu"\n        }  \n]\n',
		Station_Code: 'SAR',
		Station_Contacts: '044 - 23792260',
		Station_Id: '212',
		Station_Latitude: 13.062058,
		Station_LineColour: 'Green',
		Station_LongName: 'Arumbakkam',
		Station_Longitude: 80.211581,
		Station_Priority: 3,
		Station_ShortName: 'Arumbakkam',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			'[ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Forum Mall, Vadapalani Bus Dippo"\n        },\n{\n            "gate": "GATE B",\n            "towards": "Towards Vadapalani Murugan kovil, Kodambakkam"\n        } \n]',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "St.Thomas Mount"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Koyambedu"\n        }  \n]\n',
		Station_Code: 'SVA',
		Station_Contacts: '044 - 23792250',
		Station_Id: '213',
		Station_Latitude: 13.050825,
		Station_LineColour: 'Green',
		Station_LongName: 'Vadapalani',
		Station_Longitude: 80.212242,
		Station_Priority: 4,
		Station_ShortName: 'Vadapalani',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Udhayam Theatre, K.K.Nagar Fire station"\n        }\n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "St.Thomas Mount"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Koyambedu"\n        }  \n]\n',
		Station_Code: 'SAN',
		Station_Contacts: '044 - 23792240',
		Station_Id: '214',
		Station_Latitude: 13.035534,
		Station_LineColour: 'Green',
		Station_LongName: 'Ashok Nagar',
		Station_Longitude: 80.21114,
		Station_Priority: 5,
		Station_ShortName: 'Ashok Nagar',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			' [ \n    {\n            "gate": "GATE A",\n            "towards": "Towards Hilton Hotel side, Ambal Nagar"\n        },\n{\n            "gate": "GATE B",\n            "towards": "Towards Cipet side"\n        }\n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "St.Thomas Mount"\n        },\n    {\n            "level": "Level 1",\n            "towards": "Koyambedu"\n        }  \n]\n',
		Station_Code: 'SSI',
		Station_Contacts: '044 - 23792230',
		Station_Id: '215',
		Station_Latitude: 13.017044,
		Station_LineColour: 'Green',
		Station_LongName: 'Ekkattuthangal',
		Station_Longitude: 80.20594,
		Station_Priority: 6,
		Station_ShortName: 'Ekkattuthangal',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions:
			'[\n        {\n            "gate": "GATE A",\n            "towards": "Towards Alandur, Police quarters"\n        },\n    {\n            "gate": "GATE B",\n            "towards": "Towards Sub-Urban Railway Station, Adambakkam"\n        }  \n]\n',
		Platform_Info:
			' [\n        {\n            "level": "Level 1",\n            "towards": "-"\n        },\n    {\n            "level": "Level 1",\n            "towards": "St.Thomas Mount"\n        }  \n]\n',
		Station_Code: 'SMM',
		Station_Contacts: '044 - 23792051',
		Station_Id: '217',
		Station_Latitude: 12.995128,
		Station_LineColour: 'Blue',
		Station_LongName: 'St. Thomas Mount',
		Station_Longitude: 80.19864,
		Station_Priority: 13,
		Station_ShortName: 'St. Thomas Mount',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STC',
		Station_Contacts: '044-23792091',
		Station_Id: '149',
		Station_Latitude: 13.116,
		Station_LineColour: 'Blue',
		Station_LongName: 'Thiyagaraya College Metro',
		Station_Longitude: 80.284,
		Station_Priority: 33,
		Station_ShortName: 'Thiyagaraya College Metro',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STR',
		Station_Contacts: '044-23792092',
		Station_Id: '148',
		Station_Latitude: 13.124,
		Station_LineColour: 'Blue',
		Station_LongName: 'Tondiarpet Metro',
		Station_Longitude: 80.289,
		Station_Priority: 34,
		Station_ShortName: 'Tondiarpet Metro',
		Station_Type: 'Underground'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SNW',
		Station_Contacts: '044-23792093',
		Station_Id: '147',
		Station_Latitude: 13.107064,
		Station_LineColour: 'Blue',
		Station_LongName: 'New Washermenpet Metro',
		Station_Longitude: 80.280528,
		Station_Priority: 35,
		Station_ShortName: 'New Washermenpet Metro',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STG',
		Station_Contacts: '044-23792094',
		Station_Id: '146',
		Station_Latitude: 13.143,
		Station_LineColour: 'Blue',
		Station_LongName: 'Tollgate Metro',
		Station_Longitude: 80.296,
		Station_Priority: 36,
		Station_ShortName: 'Tollgate Metro',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SKP',
		Station_Contacts: '044-23792095',
		Station_Id: '145',
		Station_Latitude: 13.151,
		Station_LineColour: 'Blue',
		Station_LongName: 'Kaladipet Metro',
		Station_Longitude: 80.299,
		Station_Priority: 37,
		Station_ShortName: 'Kaladipet Metro',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STV',
		Station_Contacts: '044-23792097',
		Station_Id: '143',
		Station_Latitude: 13.172095,
		Station_LineColour: 'Blue',
		Station_LongName: 'Thiruvotriyur Metro',
		Station_Longitude: 83.30544,
		Station_Priority: 38,
		Station_ShortName: 'Thiruvotriyur Metro',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SWN',
		Station_Contacts: '044-23792098',
		Station_Id: '142',
		Station_Latitude: 13.18304032,
		Station_LineColour: 'Blue',
		Station_LongName: 'Wimco Nagar Metro',
		Station_Longitude: 80.30903569,
		Station_Priority: 39,
		Station_ShortName: 'Wimco Nagar Metro',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'SWD',
		Station_Contacts: '044-23792099',
		Station_Id: '141',
		Station_Latitude: 13.1842985,
		Station_LineColour: 'Blue',
		Station_LongName: 'Wimco Nagar Depot Station',
		Station_Longitude: 80.30909273,
		Station_Priority: 38,
		Station_ShortName: 'Wimco Nagar Depot Station',
		Station_Type: 'Elevated'
	},
	{
		Gates_Directions: null,
		Platform_Info: null,
		Station_Code: 'STT',
		Station_Contacts: '044-23792096',
		Station_Id: '144',
		Station_Latitude: 13.15977258,
		Station_LineColour: 'Blue',
		Station_LongName: 'Thiruvottriyur Theradi Metro',
		Station_Longitude: 80.30244886,
		Station_Priority: 39,
		Station_ShortName: 'Thiruvottriyur Theradi Metro',
		Station_Type: 'Elevated'
	}
];
