# fly.toml app configuration file generated for cmrl-web3 on 2023-07-13T09:30:47+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cmrl-web3"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
